# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 08:54
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_auto_20171113_1313'), ('core', '0003_auto_20171113_1543'), ('core', '0004_auto_20171113_1554'), ('core', '0005_transaction_currency'), ('core', '0006_auto_20171114_0817'), ('core', '0007_auto_20171114_1448')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('amount', core.models.MoneyField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('activetransaction', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('activetransactions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='actif',
            new_name='active',
        ),
        migrations.AddField(
            model_name='transaction',
            name='initial_currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar US'), ('JPY', 'Yen')], default='EUR', max_length=3),
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='initial_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='converted_amount',
            field=core.models.MoneyField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
