# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 13:13
from __future__ import unicode_literals

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=core.models.MoneyField(),
        ),
    ]
