# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171113_1313'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('activetransaction', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
