# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171113_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar US'), ('JPY', 'Yen')], default='EUR', max_length=3),
        ),
    ]
