# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 08:17
from __future__ import unicode_literals

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='initial_amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='currency',
            new_name='initial_currency',
        ),
        migrations.AddField(
            model_name='transaction',
            name='converted_amount',
            field=core.models.MoneyField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
